// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: video

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void xAxis_Animation( lv_obj_t *TargetObject, int delay);
void yAxis_Animation( lv_obj_t *TargetObject, int delay);
void ui_event_videoScreen( lv_event_t * e);
lv_obj_t *ui_videoScreen;
lv_obj_t *ui_colorPanel;
lv_obj_t *ui_logoImage;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_bg[3] = {&ui_img_bg1_png, &ui_img_bg2_png, &ui_img_bg3_png};
const lv_img_dsc_t *ui_imgset_btn_bg_[3] = {&ui_img_btn_bg_1_png, &ui_img_btn_bg_2_png, &ui_img_btn_bg_3_png};
const lv_img_dsc_t *ui_imgset_call[2] = {&ui_img_call1_png, &ui_img_call2_png};
const lv_img_dsc_t *ui_imgset_dvd_tr[1] = {&ui_img_dvd_tr1_png};
const lv_img_dsc_t *ui_imgset_372661864[7] = {&ui_img_602206286, &ui_img_602205261, &ui_img_602199888, &ui_img_602207311, &ui_img_602200913, &ui_img_602195540, &ui_img_602202963};
const lv_img_dsc_t *ui_imgset_dy[1] = {&ui_img_dy4_png};
const lv_img_dsc_t *ui_imgset_electron_[1] = {&ui_img_electron_32_png};
const lv_img_dsc_t *ui_imgset_heart[1] = {&ui_img_heart2_png};
const lv_img_dsc_t *ui_imgset_kb_[2] = {&ui_img_kb_1_png, &ui_img_kb_2_png};
const lv_img_dsc_t *ui_imgset_kg_[2] = {&ui_img_kg_1_png, &ui_img_kg_2_png};
const lv_img_dsc_t *ui_imgset_k_[2] = {&ui_img_k_1_png, &ui_img_k_2_png};
const lv_img_dsc_t *ui_imgset_419715717[8] = {&ui_img_229834011, &ui_img_229835036, &ui_img_229827613, &ui_img_229828638, &ui_img_229838359, &ui_img_229839384, &ui_img_229831961, &ui_img_229832986};
const lv_img_dsc_t *ui_imgset_s[9] = {&ui_img_s1_png, &ui_img_s2_png, &ui_img_s3_png, &ui_img_s4_png, &ui_img_s5_png, &ui_img_s6_png, &ui_img_s7_png, &ui_img_s8_png, &ui_img_s9_png};
const lv_img_dsc_t *ui_imgset_wave[2] = {&ui_img_wave1_png, &ui_img_wave2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void xAxis_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 7200);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 0, 360 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 7200);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);

}
void yAxis_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 5000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, 0, 250 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 5000);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_videoScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      xAxis_Animation(ui_colorPanel, 0);
      yAxis_Animation(ui_colorPanel, 0);
}
}

///////////////////// SCREENS ////////////////////
void ui_videoScreen_screen_init(void)
{
ui_videoScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_videoScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_videoScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_videoScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_colorPanel = lv_obj_create(ui_videoScreen);
lv_obj_set_width( ui_colorPanel, 120);
lv_obj_set_height( ui_colorPanel, 70);
lv_obj_clear_flag( ui_colorPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_colorPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_colorPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_colorPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_colorPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_logoImage = lv_img_create(ui_colorPanel);
lv_img_set_src(ui_logoImage, &ui_img_dvd_tr1_png);
lv_obj_set_width( ui_logoImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_logoImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_logoImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_logoImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_logoImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_videoScreen, ui_event_videoScreen, LV_EVENT_ALL, NULL);

}

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_videoScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_videoScreen);
}
