// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: video

#ifndef _VIDEO_UI_H
#define _VIDEO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_events.h"
void xAxis_Animation( lv_obj_t *TargetObject, int delay);
void yAxis_Animation( lv_obj_t *TargetObject, int delay);
void ui_event_videoScreen( lv_event_t * e);
extern lv_obj_t *ui_videoScreen;
extern lv_obj_t *ui_colorPanel;
extern lv_obj_t *ui_logoImage;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_dvd_tr1_png);   // assets\dvd_tr1.png
LV_IMG_DECLARE( ui_img_bg1_png);   // assets\bg1.png
LV_IMG_DECLARE( ui_img_bg2_png);   // assets\bg2.png
LV_IMG_DECLARE( ui_img_bg3_png);   // assets\bg3.png
LV_IMG_DECLARE( ui_img_btn_bg_1_png);   // assets\btn_bg_1.png
LV_IMG_DECLARE( ui_img_btn_bg_2_png);   // assets\btn_bg_2.png
LV_IMG_DECLARE( ui_img_btn_bg_3_png);   // assets\btn_bg_3.png
LV_IMG_DECLARE( ui_img_call1_png);   // assets\call1.png
LV_IMG_DECLARE( ui_img_call2_png);   // assets\call2.png
LV_IMG_DECLARE( ui_img_602206286);   // assets\dy-0.png
LV_IMG_DECLARE( ui_img_602205261);   // assets\dy-1.png
LV_IMG_DECLARE( ui_img_602199888);   // assets\dy-2.png
LV_IMG_DECLARE( ui_img_602207311);   // assets\dy-3.png
LV_IMG_DECLARE( ui_img_602200913);   // assets\dy-5.png
LV_IMG_DECLARE( ui_img_602195540);   // assets\dy-6.png
LV_IMG_DECLARE( ui_img_602202963);   // assets\dy-7.png
LV_IMG_DECLARE( ui_img_dy4_png);   // assets\dy4.png
LV_IMG_DECLARE( ui_img_electron_32_png);   // assets\electron_32.png
LV_IMG_DECLARE( ui_img_heart2_png);   // assets\heart2.png
LV_IMG_DECLARE( ui_img_kb_1_png);   // assets\kb_1.png
LV_IMG_DECLARE( ui_img_kb_2_png);   // assets\kb_2.png
LV_IMG_DECLARE( ui_img_kg_1_png);   // assets\kg_1.png
LV_IMG_DECLARE( ui_img_kg_2_png);   // assets\kg_2.png
LV_IMG_DECLARE( ui_img_k_1_png);   // assets\k_1.png
LV_IMG_DECLARE( ui_img_k_2_png);   // assets\k_2.png
LV_IMG_DECLARE( ui_img_229834011);   // assets\nt-0.png
LV_IMG_DECLARE( ui_img_229835036);   // assets\nt-1.png
LV_IMG_DECLARE( ui_img_229827613);   // assets\nt-2.png
LV_IMG_DECLARE( ui_img_229828638);   // assets\nt-3.png
LV_IMG_DECLARE( ui_img_229838359);   // assets\nt-4.png
LV_IMG_DECLARE( ui_img_229839384);   // assets\nt-5.png
LV_IMG_DECLARE( ui_img_229831961);   // assets\nt-6.png
LV_IMG_DECLARE( ui_img_229832986);   // assets\nt-7.png
LV_IMG_DECLARE( ui_img_s1_png);   // assets\s1.png
LV_IMG_DECLARE( ui_img_s2_png);   // assets\s2.png
LV_IMG_DECLARE( ui_img_s3_png);   // assets\s3.png
LV_IMG_DECLARE( ui_img_s4_png);   // assets\s4.png
LV_IMG_DECLARE( ui_img_s5_png);   // assets\s5.png
LV_IMG_DECLARE( ui_img_s6_png);   // assets\s6.png
LV_IMG_DECLARE( ui_img_s7_png);   // assets\s7.png
LV_IMG_DECLARE( ui_img_s8_png);   // assets\s8.png
LV_IMG_DECLARE( ui_img_s9_png);   // assets\s9.png
LV_IMG_DECLARE( ui_img_wave1_png);   // assets\wave1.png
LV_IMG_DECLARE( ui_img_wave2_png);   // assets\wave2.png


LV_FONT_DECLARE( ui_font_bolld_100);
LV_FONT_DECLARE( ui_font_Font1);
LV_FONT_DECLARE( ui_font_regular100);
LV_FONT_DECLARE( ui_font_regular_120);
LV_FONT_DECLARE( ui_font_semi100);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
